// Real agent screens, captured through ConPTY and xterm 6 (the terminal Anbo
// runs) and read as physical rows, bottom 24 rows kept. Paths and the account
// are redacted. Claude Code 2.1.284, Codex 0.157.1, Kimi Code 2.1.1,
// Antigravity 1.2.11, OpenCode 1.18.32. Captured 2026-09-28.

/** trust prompt on first launch */
export const claudeTrust: readonly string[] = [
  "PS D:\\work\\demo",
  "> claude",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Accessing workspace:",
  "",
  " D:\\work\\demo",
  "",
  " Quick safety check: Is this a project you created or one you trust? (Like your own code, a well-known open source",
  " project, or work from your team). If not, take a moment to review what's in this folder first.",
  "",
  " Claude Code'll be able to read, edit, and execute files here.",
  "",
  " Security guide",
  "",
  "   No, exit",
  " ❯ Yes, I trust this folder",
  "",
  " Enter to confirm · Esc to cancel",
];

/** idle composer, auto mode */
export const claudeIdleAuto: readonly string[] = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                     ◉ xhigh · /effort",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  '❯ Try "create a util logging.py that..."',
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "",
  "  ⏵⏵ auto mode on (shift+tab to cycle) · ← 1 agent",
];

/** spinner while thinking */
export const claudeThinking: readonly string[] = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "* Baking… (2s · thinking with xhigh effort)",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [··········] 0% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00",
  "  ⏸ manual mode on · ← 1 agent",
];

/** short turn finished, manual mode */
export const claudeFinishedShort: readonly string[] = [
  "● Jakarta",
  "",
  "✻ Churned for 3s · done 7:30 PM",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [41K/137] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 0m",
  "  ⏸ manual mode on · ← 1 agent",
];

/** permission to create a file */
export const claudeCreateDialog: readonly string[] = [
  "",
  "",
  "❯ Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "● Jakarta",
  "",
  "✻ Churned for 3s · done 7:30 PM",
  "",
  "❯ Buat file catatan.txt berisi kata halo saja. Jangan lakukan hal lain.",
  "",
  "● Write(catatan.txt)",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Create file",
  " catatan.txt",
  "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌",
  "  1 halo",
  "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌",
  " Do you want to create catatan.txt?",
  " ❯ 1. Yes",
  "   2. Yes, and switch to accept edits (auto-approve file edits and common file commands) for this session (shift+tab)",
  "   3. No",
  "",
  " Esc to cancel · Tab to amend",
];

/** permission to overwrite a file */
export const claudeOverwriteDialog: readonly string[] = [
  "",
  "● File catatan.txt sudah dibuat dan hanya berisi kata halo.",
  "",
  "✻ Sautéed for 5s · done 7:31 PM",
  "",
  "❯ Ganti isi catatan.txt menjadi kata dunia. Jangan lakukan hal lain.",
  "",
  "● Write(catatan.txt)",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " Overwrite file",
  " catatan.txt",
  "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌",
  "  1 -halo",
  "  1   No newline at end of file",
  "  2 +dunia",
  "  3   No newline at end of file",
  "╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌",
  " Do you want to overwrite catatan.txt?",
  " ❯ 1. Yes",
  "   2. Yes, and switch to accept edits (auto-approve file edits and common file commands) for this session (shift+tab)",
  "   3. No",
  "",
  " Esc to cancel · Tab to amend",
];

/** shell command running */
export const claudeToolRunning: readonly string[] = [
  "● Write(catatan.txt)",
  "  ⎿  Added 1 line, removed 1 line",
  "      1 -halo",
  "      1   No newline at end of file",
  "      2 +dunia",
  "      3   No newline at end of file",
  "",
  "● Isi catatan.txt sudah diganti. Sekarang file itu hanya berisi kata dunia.",
  "",
  "✻ Baked for 4s · done 7:32 PM",
  "",
  "❯ Jalankan perintah PowerShell ini persis lewat tool Bash/PowerShell: Start-Sleep -Seconds 8; Write-Output selesai.",
  "  Setelah itu jawab singkat.",
  "",
  "● Running 1 shell command…",
  "",
  "✻ Orbiting…",
  "  ⎿  Tip: Use /memory to view and manage Claude memory",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/42] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 1m",
  "  ⏸ manual mode on · ← 1 agent",
];

/** finished; the answer quotes dialog words */
export const claudeFinishedProse: readonly string[] = [
  "",
  "❯ Jalankan perintah PowerShell ini persis lewat tool Bash/PowerShell: Start-Sleep -Seconds 8; Write-Output selesai.",
  "  Setelah itu jawab singkat.",
  "",
  "  Ran 1 shell command",
  "",
  "● Perintahnya sudah jalan dan keluarannya selesai.",
  "",
  "✻ Brewed for 26s · done 7:32 PM",
  "",
  "❯ Tanpa menjalankan tool apa pun, tulis ulang persis 3 baris ini: This action requires approval and needs your input. /",
  "  Press Enter to continue. / Would you like to proceed? Do you want to allow it to run?",
  "",
  "● This action requires approval and needs your input.",
  "  Press Enter to continue.",
  "  Would you like to proceed? Do you want to allow it to run?",
  "",
  "✻ Churned for 2s · done 7:33 PM",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/77] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 3m",
  "  ⏸ manual mode on · ← 1 agent",
];

/** AskUserQuestion */
export const claudeQuestion: readonly string[] = [
  "  Press Enter to continue. / Would you like to proceed? Do you want to allow it to run?",
  "",
  "● This action requires approval and needs your input.",
  "  Press Enter to continue.",
  "  Would you like to proceed? Do you want to allow it to run?",
  "",
  "✻ Churned for 2s · done 7:33 PM",
  "",
  "❯ Pakai tool AskUserQuestion untuk menanyakan saya: pilih warna Merah atau Biru. Setelah saya jawab, balas satu",
  "  kalimat.",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " ☐ Warna",
  "",
  "Pilih warna: Merah atau Biru?",
  "",
  "  1. Merah",
  "     Pilih warna merah",
  "❯ 2. Biru",
  "     Pilih warna biru",
  "  3. Type something.",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  4. Chat about this",
  "",
  "Enter to select · ↑/↓ to navigate · Esc to cancel",
];

/** streaming a long answer */
export const claudeStreaming: readonly string[] = [
  "  Would you like to proceed? Do you want to allow it to run?",
  "",
  "✻ Churned for 2s · done 7:33 PM",
  "",
  "❯ Pakai tool AskUserQuestion untuk menanyakan saya: pilih warna Merah atau Biru. Setelah saya jawab, balas satu",
  "  kalimat.",
  "",
  "● User answered Claude's questions:",
  "  ⎿  · Pilih warna: Merah atau Biru? → Biru",
  "",
  "● Anda memilih warna Biru.",
  "",
  "✻ Sautéed for 4s · done 7:34 PM",
  "",
  "❯ Tulis angka 1 sampai 400, satu angka per baris, tanpa tool dan tanpa kode.",
  "",
  "· Beaming… (2s · ↓ 169 tokens · thinking with xhigh effort)",
  "  ⎿  Tip: Did you know you can drag and drop image files into your terminal?",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/14] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 3m",
  "  ⏸ manual mode on · ← 1 agent",
];

/** turn interrupted with Esc */
export const claudeInterrupted: readonly string[] = [
  "  306",
  "  307",
  "  308",
  "  309",
  "  310",
  "  311",
  "  312",
  "  313",
  "  314",
  "  315",
  "  316",
  "  317",
  "  318",
  "  319",
  "  320",
  "  321",
  "  322",
  "  ⎿  Interrupted · What should Claude do instead?",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/8] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 4m",
  "  ⏸ plan mode on (shift+tab to cycle) · ← 1 agent",
];

/** plan ready for approval */
export const claudePlanApproval: readonly string[] = [
  "  ╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌",
  "   Rencana: tambah b.txt",
  "",
  "   Konteks",
  "",
  "   Pengguna ingin file baru b.txt yang hanya berisi kata ok.",
  "",
  "   Langkah",
  "",
  "   1. Buat file b.txt di direktori kerja (D:\\work\\demo",
  "      demo) dengan tool Write.",
  "   2. Isi file hanya dengan kata ok.",
  "",
  "   Verifikasi",
  "                                                                                                                      ↓",
  "  ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "   Claude has written up a plan and is ready to execute. Would you like to proceed?",
  "",
  "   ❯ 1. Yes, and use auto mode",
  "     2. Yes, manually approve edits",
  "     3. Tell Claude what to change",
  "        shift+tab to approve with this feedback",
  "",
  "   ctrl+g to edit in Notepad · ~\\.claude\\plans\\plan.md",
];

/** after /clear */
export const claudeCleared: readonly string[] = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [··········] 0% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 0m",
  "  ⏵⏵ auto mode on (shift+tab to cycle) · ← 1 agent",
];

/** idle composer, bypass mode */
export const claudeIdleBypass: readonly string[] = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                                                                     ◉ xhigh · /effort",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  '❯ Try "write a test for <filepath>"',
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "",
  "  ⏵⏵ bypass permissions on (shift+tab to cycle) · ← 1 agent",
];

/** turn over, a background shell still running */
export const claudeBackgroundShell: readonly string[] = [
  "  Ran 1 shell command",
  "",
  '● Perintahnya sudah jalan dan mengeluarkan "beres" setelah jeda 10 detik.',
  "",
  "✻ Worked for 29s · done 7:38 PM · 1 shell still running",
  "",
  "❯ Jalankan perintah PowerShell Start-Sleep -Seconds 45 sebagai background task (run_in_background true), jangan",
  "  ditunggu, langsung jawab satu kata: oke.",
  "",
  "  Ran 1 shell command",
  "",
  "● oke",
  "",
  "✻ Sautéed for 14s · done 7:39 PM · 1 shell still running",
  "",
  "",
  "",
  "",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯ cek status background task tadi",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [41K/119] 4% | 5h: ·········· 4% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 1m",
  "  ⏵⏵ bypass permissions on · 1 shell · ← 1 agent",
];

/** finished at 80 columns */
export const claudeNarrowFinished: readonly string[] = [
  "",
  "● oke",
  "",
  "✻ Sautéed for 14s · done 7:39 PM",
  "",
  '● Background command "Wait 45 seconds in the background" completed (exit code 0)',
  "",
  "● Tugas background Start-Sleep -Seconds 45 sudah selesai tanpa error.",
  "",
  "✻ Cogitated for 2s · done 7:40 PM",
  "",
  "❯ Sebutkan 3 nama planet, satu per baris, tanpa tool.",
  "",
  "● Merkurius",
  "  Venus",
  "  Mars",
  "",
  "✻ Cooked for 1s · done 7:40 PM",
  "",
  "────────────────────────────────────────────────────────────────────────────────",
  "❯",
  "────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/53] 4% | 5h: ·········· 5% ↻ 23:30 | 7d: ████···…",
  "  ⏵⏵ bypass permissions on (shift+tab to cycle) · ← 1 agent",
];

/** finished at 200 columns, prompt suggestion shown */
export const claudeWideFinished: readonly string[] = [
  "✻ Cogitated for 2s · done 7:40 PM",
  "",
  "❯ Sebutkan 3 nama planet, satu per baris, tanpa tool.",
  "",
  "● Merkurius",
  "  Venus",
  "  Mars",
  "",
  "✻ Cooked for 1s · done 7:40 PM",
  "",
  "❯ Sebutkan 2 nama benua, satu per baris, tanpa tool.",
  "",
  "● Asia",
  "  Afrika",
  "",
  "✻ Worked for 1s · done 7:40 PM",
  "",
  "",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "❯ Sebutkan 3 nama warna, satu per baris, tanpa tool.",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Opus 5.5 Xhigh | ctx: [42K/10] 4% | 5h: ·········· 5% ↻ 23:30 | 7d: ████······ 42% ↻ Fri 11:00 | ▸ 2m",
  "  ⏵⏵ bypass permissions on (shift+tab to cycle) · ← 1 agent",
];

/** trust prompt */
export const codexTrust: readonly string[] = [
  "",
  "  Folder access",
  "  D:\\work\\demo",
  "",
  "  Trust this folder? Codex can read, edit, and run files here, subject to your permission settings. Folder settings",
  "  can run code automatically, even without a model request. Continue only if you trust these files. Your trust",
  "  decision will be saved.",
  "",
  "› 1. Trust and continue",
  "  2. Quit",
  "",
  "  enter continue · esc quit",
];

/** idle composer */
export const codexIdle: readonly string[] = [
  "",
  "╭───────────────────────────────────────────────────╮",
  "│ >_ OpenAI Codex (v0.157.1)                        │",
  "│                                                   │",
  "│ model:     loading   /model to change             │",
  "│ directory: D:\\work\\demo…\\ws\\codex │",
  "╰───────────────────────────────────────────────────╯",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "                                                 Tip: Use /status to see the current model, approvals, and token usage.",
  "",
  "› Ask Codex to do anything",
  "",
  "  GPT-6-Astra default · D:\\work\\demo…",
  "  ? for shortcuts",
];

/** status row while working */
export const codexWorking: readonly string[] = [
  "",
  "╭───────────────────────────────────────────────────╮",
  "│ >_ OpenAI Codex (v0.157.1)                        │",
  "│                                                   │",
  "│ model:     GPT-6-Astra xhigh   /model to change   │",
  "│ directory: D:\\work\\demo…\\ws\\codex │",
  "╰───────────────────────────────────────────────────╯",
  "",
  "",
  "› Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "• Working (1s • esc to interrupt)",
  "",
  "",
  "› Ask Codex to do anything",
  "",
  "  GPT-6-Astra xhigh · D:\\work\\demo…",
  "  ? for shortcuts",
];

/** short turn finished with a time row */
export const codexFinishedShort: readonly string[] = [
  "╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  "",
  "╭───────────────────────────────────────────────────╮",
  "│ >_ OpenAI Codex (v0.157.1)                        │",
  "│                                                   │",
  "│ model:     GPT-6-Astra xhigh   /model to change   │",
  "│ directory: D:\\work\\demo…\\ws\\codex │",
  "╰───────────────────────────────────────────────────╯",
  "",
  "",
  "› Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "",
  "• Jakarta",
  "",
  "  19:43",
  "",
  "",
  "",
  "",
  "",
  "› Ask Codex to do anything",
  "",
  "  GPT-6-Astra xhigh · D:\\work\\demo…",
];

/** a mistyped slash command, no model turn */
export const codexUnknownCommand: readonly string[] = [
  "╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  "",
  "╭───────────────────────────────────────────────────╮",
  "│ >_ OpenAI Codex (v0.157.1)                        │",
  "│                                                   │",
  "│ model:     GPT-6-Astra xhigh   /model to change   │",
  "│ directory: D:\\work\\demo…\\ws\\codex │",
  "╰───────────────────────────────────────────────────╯",
  "",
  "",
  "› Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "",
  "• Jakarta",
  "",
  "  19:43",
  "",
  "• Unrecognized command '/approvals'. Type \"/\" for a list of supported commands.",
  "",
  "",
  "",
  "› //approvals",
  "",
  "  GPT-6-Astra xhigh · D:\\work\\demo…",
];

/** commentary streaming with no status row */
export const codexCommentary: readonly string[] = [
  "",
  "",
  "• Saya akan membuat catatan.txt menggunakan Set-Content.",
  "",
  "✔ You approved codex to run Set-Content -LiteralPath 'catatan.txt' -Value 'halo' -NoNewline this time",
  "",
  "• Ran Set-Content -LiteralPath 'catatan.txt' -Value 'halo' -NoNewline",
  "  └ (no output)",
  "",
  "• catatan.txt dibuat berisi halo.",
  "",
  "  19:45",
  "",
  "",
  "› Jalankan perintah PowerShell Start-Sleep -Seconds 30 lalu jawab selesai.",
  "",
  "",
  "• Saya akan menjalankan per",
  "",
  "",
  "› Ask Codex to do anything",
  "",
  "  GPT-6-Astra xhigh · D:\\work\\demo…",
  "  ? for shortcuts",
];

/** command approval */
export const codexApproval: readonly string[] = [
  "",
  "› Buat file catatan.txt berisi kata halo dengan menjalankan perintah PowerShell Set-Content. Jangan lakukan hal lain.",
  "",
  "",
  "• Saya akan membuat catatan.txt menggunakan Set-Content.",
  "",
  "• Running Set-Content -LiteralPath 'catatan.txt' -Value 'halo' -NoNewline",
  "",
  "",
  "  Would you like to run the following command?",
  "",
  "  Environment: local",
  "",
  "  Reason: Izinkan pembuatan catatan.txt berisi halo? Sandbox saat ini hanya mengizinkan pembacaan.",
  "",
  "  $ Set-Content -LiteralPath 'catatan.txt' -Value 'halo' -NoNewline",
  "",
  "",
  "› 1. Yes, proceed (y)",
  "  2. Yes, and don't ask again for commands that start with `Set-Content -LiteralPath catatan.txt -Value halo -NoNewline`",
  "     (p)",
  "  3. No, and tell Codex what to do differently (esc)",
  "",
  "  Press enter to confirm or esc to cancel",
];

/** the /permissions menu the user opened */
export const codexPermissionsMenu: readonly string[] = [
  "› Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "",
  "• Jakarta",
  "",
  "  19:43",
  "",
  "• Unrecognized command '/approvals'. Type \"/\" for a list of supported commands.",
  "",
  "",
  "  Update Model Permissions",
  "",
  "",
  "› 1. Read Only                                       Read workspace files, with approval required for edits or internet",
  "                                                     access",
  "  2. Ask for approval (non-admin sandbox) (current)  Read and edit workspace files and run commands, with approval",
  "                                                     required for internet access or edits outside the workspace",
  "  3. Approve for me                                  Only ask for actions detected as potentially unsafe",
  "  4. Full Access                                     Use with caution: Codex can edit files outside this workspace and",
  "                                                     access the internet without approval",
  "",
  "  The non-admin sandbox protects your files and prevents network access under most circumstances. However, it carries",
  "  greater risk if prompt injected. To upgrade to the default sandbox, run /setup-default-sandbox.",
  "  enter select · esc back",
];

/** interrupted, background terminal left running */
export const codexInterrupted: readonly string[] = [
  "• Ran Set-Content -LiteralPath 'catatan.txt' -Value 'halo' -NoNewline",
  "  └ (no output)",
  "",
  "• catatan.txt dibuat berisi halo.",
  "",
  "  19:45",
  "",
  "",
  "› Jalankan perintah PowerShell Start-Sleep -Seconds 30 lalu jawab selesai.",
  "",
  "",
  "• Saya akan menjalankan perintah tersebut.",
  "",
  "■ Conversation interrupted - tell the model what to do differently. Something went wrong? Hit `/feedback` to report the",
  "issue.",
  "",
  "  1 background terminal running · /ps to view · /stop to close",
  "",
  "                                                       Tip: You can run any shell command from Codex using ! (e.g. !ls)",
  "",
  "› Ask Codex to do anything",
  "",
  "  GPT-6-Astra xhigh · D:\\work\\demo…",
  "  ? for shortcuts",
];

/** trust prompt */
export const kimiTrust: readonly string[] = [
  "PS D:\\work\\demo",
  "imi --auto",
  " ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  Trust this folder?",
  "  ↑↓ navigate · Enter select · Esc exit",
  "",
  "  D:\\work\\demo",
  "",
  "  Project-level MCP servers are disabled until you explicitly choose Trust. Trust starts the listed project MCP",
  "  targets and remembers this folder.",
  "",
  "   ❯ Trust this folder",
  "     Enable project MCP servers. Remembered for this folder.",
  "",
  "     Don't trust",
  "     Exit Kimi Code. Asked again next launch.",
  "",
  " ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
];

/** idle composer */
export const kimiIdle: readonly string[] = [
  "imi --auto",
  "",
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │                                                                                                                    │",
  " │  ▐█▛█▛█▌  Welcome to Kimi Code!                                                                                    │",
  " │  ▐█████▌  Send /help for help information.                                                                         │",
  " │                                                                                                                    │",
  " │  Directory: D:\\work\\demo…│",
  " │  Session:                                                                                                          │",
  " │  Model:     GLM-5.3                                                                                                │",
  " │  Version:   2.1.1                                                                                                  │",
  " │                                                                                                                    │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  "",
  " ✦ Kimi Code Desktop is here — Everything you love about Kimi Code, now on desktop",
  "   Run /desktop or visit https://www.kimi.com/code to install",
  "",
  "   No session yet — one will be created on your first message.",
  "",
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │ >                                                                                                                  │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  " Never Ask  GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                                   context: 0% (0/977k)",
];

/** moon row while working */
export const kimiMoon: readonly string[] = [
  " │                                                                                                                    │",
  " │  ▐█▛█▛█▌  Welcome to Kimi Code!                                                                                    │",
  " │  ▐█████▌  Send /help for help information.                                                                         │",
  " │                                                                                                                    │",
  " │  Directory: D:\\work\\demo…│",
  " │  Session:   session_78282f48-0906-4db7-99db-cf412f99e380                                                           │",
  " │  Model:     GLM-5.3                                                                                                │",
  " │  Version:   2.1.1                                                                                                  │",
  " │                                                                                                                    │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  "",
  " ✦ Kimi Code Desktop is here — Everything you love about Kimi Code, now on desktop",
  "   Run /desktop or visit https://www.kimi.com/code to install",
  "",
  "   No session yet — one will be created on your first message.",
  "",
  " ✨ Jawab satu kata saja: ibu kota Indonesia?",
  "",
  '  🌔 · Tip: ask Kimi to schedule tasks, e.g. "remind me at 5pm"',
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │ >                                                                                                                  │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  " Never Ask  GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                                   context: 0% (0/977k)",
];

/** spinner while streaming */
export const kimiSpinner: readonly string[] = [
  "   97",
  "   98",
  "   99",
  "   100",
  "   101",
  "   102",
  "   103",
  "   104",
  "   105",
  "   106",
  "   107",
  "   108",
  "   109",
  "   110",
  "   111",
  "   112",
  "   113",
  "",
  '  ⠧ Working… · Tip: ask Kimi to schedule tasks, e.g. "remind me at 5pm"',
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │ >                                                                                                                  │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  " Never Ask  GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                               context: 2% (19.5k/977k)",
];

/** command approval */
export const kimiApproval: readonly string[] = [
  "",
  " ✨ Jalankan perintah shell PowerShell: Start-Sleep -Seconds 10; Write-Output beres. Lalu jawab satu kalimat.",
  "",
  " ● The user wants me to run a PowerShell shell command: Start-Sleep -Seconds 10; Write-Output beres. Then answer in one",
  "   sentence.",
  "   … (5 more lines, ctrl+o to expand)",
  "",
  ' ● Running a command · $ powershell.exe -NoProfile -Command "Start-Sleep -Seconds 10; Write-Output beres"',
  " ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "   ▶ Run this command?",
  "",
  "   cwd: D:\\work\\demo",
  '   $ powershell.exe -NoProfile -Command "Start-Sleep -Seconds 10; Write-Output beres"',
  "     Run PowerShell sleep 10s then output beres",
  "",
  "   ▶ 1. Approve once",
  "     2. Approve for this session",
  "     3. Reject",
  "     4. Reject with feedback",
  "",
  "   ↑/↓ select · 1/2/3/4 choose · ↵ confirm",
  " ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  " GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                               context: 3% (20.3k/977k)",
];

/** finished after the approved command */
export const kimiFinished: readonly string[] = [
  "",
  "   Permission mode: Always Ask",
  "",
  " ✨ Jalankan perintah shell PowerShell: Start-Sleep -Seconds 10; Write-Output beres. Lalu jawab satu kalimat.",
  "",
  " ● The user wants me to run a PowerShell shell command: Start-Sleep -Seconds 10; Write-Output beres. Then answer in one",
  "   sentence.",
  "   … (5 more lines, ctrl+o to expand)",
  "",
  ' ● Ran a command · $ powershell.exe -NoProfile -Command "Start-Sleep -Seconds 10; Write-Output beres"',
  "   beres",
  "",
  '   Approved: Running: powershell.exe -NoProfile -Command "Start-Sleep -S…',
  "",
  ' ● The command ran successfully, took about 13.5 seconds, output "beres". Now answer in one sentence (satu kalimat), in',
  "   Indonesian.",
  "",
  ' ● Perintah PowerShell berhasil dijalankan selama sekitar 13,5 detik dan mengeluarkan output "beres".',
  "",
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │ >                                                                                                                  │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  " GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                               context: 3% (20.4k/977k)",
];

/** interrupted */
export const kimiInterrupted: readonly string[] = [
  " ✨ Jalankan perintah shell PowerShell: Start-Sleep -Seconds 10; Write-Output beres. Lalu jawab satu kalimat.",
  "",
  " ● The user wants me to run a PowerShell shell command: Start-Sleep -Seconds 10; Write-Output beres. Then answer in one",
  "   sentence.",
  "   … (5 more lines, ctrl+o to expand)",
  "",
  ' ● Ran a command · $ powershell.exe -NoProfile -Command "Start-Sleep -Seconds 10; Write-Output beres"',
  "   beres",
  "",
  '   Approved: Running: powershell.exe -NoProfile -Command "Start-Sleep -S…',
  "",
  ' ● The command ran successfully, took about 13.5 seconds, output "beres". Now answer in one sentence (satu kalimat), in',
  "   Indonesian.",
  "",
  ' ● Perintah PowerShell berhasil dijalankan selama sekitar 13,5 detik dan mengeluarkan output "beres".',
  "",
  " ✨ Tanpa tool, tulis angka 1 sampai 400, satu angka per baris.",
  "   Interrupted by user",
  "",
  " ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮",
  " │ >                                                                                                                  │",
  " ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯",
  " GLM-5.3 thinking: high  D:\\work\\demo…",
  "                                                                                               context: 3% (20.5k/977k)",
];

/** trust prompt */
export const agyTrust: readonly string[] = [
  "Accessing workspace:",
  "",
  "D:\\work\\demo",
  "",
  "Do you trust the contents of this project?",
  "",
  "Antigravity CLI requires permission to read, edit, and execute files here.",
  "",
  "> Yes, I trust this folder",
  "  No, exit",
  "",
  "  ↑/↓ Navigate · enter Confirm",
  "                                                                                                   Gemini 3.1 Pro · high",
];

/** idle composer */
export const agyIdle: readonly string[] = [
  "PS D:\\work\\demo a",
  "gy",
  "",
  "",
  "      ▄▀▀▄        Antigravity CLI 1.2.11",
  "     ▀▀▀▀▀▀       user@example.com (Google AI Pro)",
  "    ▀▀▀▀▀▀▀▀      Gemini 3.1 Pro (High)",
  "   ▄▀▀    ▀▀▄     D:\\work\\demo",
  "  ▄▀▀      ▀▀▄",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  ">",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "? for shortcuts                                                                                    Gemini 3.1 Pro · high",
];

/** generating */
export const agyGenerating: readonly string[] = [
  "PS D:\\work\\demo a",
  "gy",
  "",
  "",
  "      ▄▀▀▄        Antigravity CLI 1.2.11",
  "     ▀▀▀▀▀▀       user@example.com (Google AI Pro)",
  "    ▀▀▀▀▀▀▀▀      Gemini 3.1 Pro (High)",
  "   ▄▀▀    ▀▀▄     D:\\work\\demo",
  "  ▄▀▀      ▀▀▄",
  "",
  "────────────────────────────────────────────────────────────",
  "> Jawab satu kata saja: ibu kota Indonesia?",
  "⡿  Generating...",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  ">",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "esc to cancel                                                                                      Gemini 3.1 Pro · high",
];

/** command approval */
export const agyApproval: readonly string[] = [
  "",
  "────────────────────────────────────────────────────────────",
  "> Jalankan perintah PowerShell Start-Sleep -Seconds 40 sebagai background task, jangan ditunggu, langsung jawab satu",
  "  kata: oke.",
  "",
  "▸ Thought for 4s, 240 tokens",
  "  I'm now focusing on tool selection, ensuring I choose the most specific tool for each task. Before I call any tool...",
  "",
  "● Bash(Start-Sleep -Seconds 40) (ctrl+o to expand)",
  "",
  "Command",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "",
  "Requesting permission for:",
  "   Start-Sleep -Seconds 40",
  "",
  "Run this command?",
  "> 1. Yes, run command",
  "  2. Yes, and always allow in this conversation for commands that start with 'Start-Sleep -Seconds 40'",
  "  3. Yes, and always allow for commands that start with 'Start-Sleep -Seconds 40' (Persist to settings.json)",
  "  4. No, cancel",
  "",
  "  ↑/↓ Navigate · tab Amend · ctrl+g edit/expand command",
  "esc to cancel                                                                                      Gemini 3.1 Pro · high",
];

/** command done, model not resumed yet (mid-turn) */
export const agyCommandGap: readonly string[] = [
  "────────────────────────────────────────────────────────────",
  "> Jawab satu kata saja: ibu kota Indonesia?",
  "",
  "▸ Thought for 5s, 309 tokens",
  "  I'm now focusing on tool selection, ensuring I use the most appropriate ones instead of generic commands. I won't...",
  "  Nusantara",
  "",
  "────────────────────────────────────────────────────────────",
  "> Jalankan perintah PowerShell ini di terminal (bukan background): Start-Sleep -Seconds 10; Write-Output beres. Lalu",
  "  jawab satu kalimat.",
  "",
  "▸ Thought for 5s, 381 tokens",
  "  I'm now zeroing in on the `run_command` tool specifics, to correctly execute a PowerShell command. I've set `WaitM...",
  "",
  "● Bash(Start-Sleep -Seconds 10; Write-Output beres) (ctrl+o to expand)",
  "",
  "  Perintah sedang dijalankan, saya akan memberitahu Anda segera setelah selesai.",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  ">",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  ● [19:51:01] Start-Sleep -Seconds 10; Write-Output beres running",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "? for shortcuts                                                               Gemini 3.1 Pro · high · 1 task(s) · /tasks",
];

/** question */
export const agyQuestion: readonly string[] = [
  "▸ Thought for 3s, 135 tokens",
  "  I'm now focusing on tool specificity. My thinking emphasizes selecting the most precise tool available for each ta...",
  '  Perintah PowerShell telah selesai dijalankan dan berhasil mencetak output "beres" di terminal.',
  "",
  "────────────────────────────────────────────────────────────",
  "> Gunakan tool pertanyaan interaktif (ask user question), bukan teks biasa, untuk menanyakan saya: pilih Merah atau",
  "  Biru. Setelah saya jawab, balas satu kalimat.",
  "",
  "▸ Thought for 3s, 148 tokens",
  "  I'm now focusing on tool selection specificity. Before any tool call, I'm explicitly listing out all tools that mi...",
  "",
  "? Pilih Merah atau Biru?",
  "",
  "Question",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "",
  "Question 1/1: Pilih Merah atau Biru?",
  "",
  "  1. Merah",
  "> 2. Biru",
  "  3. Write-in...",
  "",
  "  ↑/↓ Navigate · enter Select · esc Skip",
  "esc to cancel                                                                                      Gemini 3.1 Pro · high",
];

/** turn over, background task running */
export const agyBackgroundTask: readonly string[] = [
  "  I'm now focusing on tool selection specificity. Before any tool call, I'm explicitly listing out all tools that mi...",
  "",
  "? Pilih Merah atau Biru?",
  "> Biru",
  "",
  "  Pilihan yang bagus, Anda telah memilih warna Biru.",
  "",
  "────────────────────────────────────────────────────────────",
  "> Jalankan perintah PowerShell Start-Sleep -Seconds 40 sebagai background task, jangan ditunggu, langsung jawab satu",
  "  kata: oke.",
  "",
  "▸ Thought for 4s, 240 tokens",
  "  I'm now focusing on tool selection, ensuring I choose the most specific tool for each task. Before I call any tool...",
  "",
  "○ Bash(Start-Sleep -Seconds 40) (ctrl+o to expand)",
  "",
  "  Oke.",
  "",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  ">",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "  ● [19:52:35] Start-Sleep -Seconds 40 running",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "? for shortcuts                                                               Gemini 3.1 Pro · high · 1 task(s) · /tasks",
];

/** interrupted */
export const agyInterrupted: readonly string[] = [
  "  220",
  "  221",
  "  222",
  "  223",
  "  224",
  "  225",
  "  226",
  "  227",
  "  228",
  "  229",
  "  230",
  "  231",
  "  232",
  "  233",
  "  234",
  "  235",
  "  236",
  "  2",
  "",
  "  ⎿  Interrupted · What should Antigravity CLI do instead?",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  ">",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "? for shortcuts                                                                                    Gemini 3.1 Pro · high",
];

/** slash-command autocomplete */
export const agyAutocomplete: readonly string[] = [
  "  223",
  "  224",
  "  225",
  "  226",
  "  227",
  "  228",
  "  229",
  "  230",
  "  231",
  "  232",
  "  233",
  "  234",
  "  235",
  "  236",
  "  2",
  "",
  "  ⎿  Interrupted · What should Antigravity CLI do instead?",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "> /quit",
  "────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────",
  "> /exit (quit)  Exit the CLI",
  "",
  "  ↑/↓ Navigate · enter Select · tab Complete",
  "esc to cancel                                                                                      Gemini 3.1 Pro · high",
];

/** idle */
export const opencodeIdle: readonly string[] = [
  "",
  "                                                                          ▄",
  "                                         █▀▀█ █▀▀█ █▀▀█ █▀▀▄ █▀▀▀ █▀▀█ █▀▀█ █▀▀█",
  "                                         █  █ █  █ █▀▀▀ █  █ █    █  █ █  █ █▀▀▀",
  "                                         ▀▀▀▀ █▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀ ▀▀▀▀",
  "",
  "",
  "                       ┃",
  '                       ┃  Ask anything… "What is the tech stack of this project?"',
  "                       ┃",
  "                       ┃  Build · Muse Spark 1.3 Free OpenCode Zen · high",
  "                       ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "                                                                       tab agents  ctrl+p commands",
  "",
  "",
  "",
  "                                ● Tip Run /connect to add an AI provider and start coding",
  "",
  "",
  "",
  "",
  "",
  "  D:\\work\\demo           1.18.32",
  "  opencode",
];

/** working */
export const opencodeWorking: readonly string[] = [
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "  ┃",
  "  ┃",
  "  ┃",
  "  ┃  Build · Muse Spark 1.3 Free OpenCode Zen · high",
  "  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "   ■■■■■⬝⬝⬝  esc interrupt                                                                 tab agents  ctrl+p commands",
];

/** first Esc pressed */
export const opencodeEscAgain: readonly string[] = [
  "     400",
  "",
  "     ▣  Build · Muse Spark 1.3 Free · 12.2s",
  "",
  "  ┃",
  '  ┃  Jalankan perintah shell ini: powershell -NoProfile -Command "Start-Sleep -Seconds 30" lalu jawab selesai.',
  "  ┃",
  "",
  "     + Thought: 3.9s",
  "",
  "     Thought · 5ms",
  "",
  "  ┃",
  '  ┃  ⠼ powershell -NoProfile -Command "Start-Sleep -Seconds 30"',
  "  ┃",
  "",
  "     ▣  Build · Muse Spark 1.3 Free",
  "",
  "  ┃",
  "  ┃",
  "  ┃",
  "  ┃  Build · Muse Spark 1.3 Free OpenCode Zen · high",
  "  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "   ⬝⬝⬝⬝⬝⬝⬝⬝  esc again to interrupt                                                        12.4K (1%)  ctrl+p commands",
];

/** finished */
export const opencodeFinished: readonly string[] = [
  "     Nusantara",
  "",
  "     ▣  Build · Muse Spark 1.3 Free · 19.5s",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "  ┃",
  '  ┃  Jalankan perintah shell ini: powershell -NoProfile -Command "Start-Sleep -Seconds 10; Write-Output beres" lalu',
  "  ┃  jawab satu kalimat.",
  "  ┃",
  "  ┃  Build · Muse Spark 1.3 Free OpenCode Zen · high",
  "  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "   D:\\work\\demo    10.6K (1% ctrl+p",
  "   scratchpad\\capture\\ws\\opencode                                                                         commands",
];

/** interrupted */
export const opencodeInterrupted: readonly string[] = [
  "",
  "     + Thought: 3.9s",
  "",
  "     Thought · 5ms",
  "",
  "  ┃",
  '  ┃  $ powershell -NoProfile -Command "Start-Sleep -Seconds 30"',
  "  ┃",
  "  ┃  (no output)",
  "  ┃",
  "  ┃  <shell_metadata>",
  "  ┃  User aborted the command",
  "  ┃  </shell_metadata>",
  "  ┃",
  "",
  "     ▣  Build · Muse Spark 1.3 Free · interrupted",
  "",
  "  ┃",
  "  ┃",
  "  ┃",
  "  ┃  Build · Muse Spark 1.3 Free OpenCode Zen · high",
  "  ╹▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀",
  "   D:\\work\\demo    12.4K (1% ctrl+p",
  "   scratchpad\\capture\\ws\\opencode                                                                         commands",
];

/** permission required */
export const opencodePermission: readonly string[] = [
  "",
  "     Thought · 251ms",
  "",
  '     $ powershell -NoProfile -Command "Start-Sleep -Seconds 5; Write-Output beres"',
  "",
  "     ▣  Build · Muse Spark 1.3 Free",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "  ┃",
  "  ┃  △ Permission required",
  "  ┃    # Shell command",
  "  ┃",
  '  ┃  $ powershell -NoProfile -Command "Start-Sleep -Seconds 5; Write-Output beres"',
  "  ┃",
  "  ┃",
  "  ┃   Allow once   Allow always   Reject                                 ctrl+f fullscreen  ⇆ select  enter confirm",
  "  ┃",
];

/** Every screen above, by name. */
export const agentScreens = {
  claudeTrust,
  claudeIdleAuto,
  claudeThinking,
  claudeFinishedShort,
  claudeCreateDialog,
  claudeOverwriteDialog,
  claudeToolRunning,
  claudeFinishedProse,
  claudeQuestion,
  claudeStreaming,
  claudeInterrupted,
  claudePlanApproval,
  claudeCleared,
  claudeIdleBypass,
  claudeBackgroundShell,
  claudeNarrowFinished,
  claudeWideFinished,
  codexTrust,
  codexIdle,
  codexWorking,
  codexFinishedShort,
  codexUnknownCommand,
  codexCommentary,
  codexApproval,
  codexPermissionsMenu,
  codexInterrupted,
  kimiTrust,
  kimiIdle,
  kimiMoon,
  kimiSpinner,
  kimiApproval,
  kimiFinished,
  kimiInterrupted,
  agyTrust,
  agyIdle,
  agyGenerating,
  agyApproval,
  agyCommandGap,
  agyQuestion,
  agyBackgroundTask,
  agyInterrupted,
  agyAutocomplete,
  opencodeIdle,
  opencodeWorking,
  opencodeEscAgain,
  opencodeFinished,
  opencodeInterrupted,
  opencodePermission,
};
